name: Build and Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev build-essential

    - name: Build and Install GTest
      run: |
        sudo apt-get install -y libgtest-dev cmake
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Configure with CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build project
      run: |
        cd build
        make

    - name: Run Tests
      run: |
        cd build
        ./test_Tank
        ./test_GameFactory

    - name: Create DEB package
      run: |
        mkdir -p package/usr/bin
        cp build/main package/usr/bin/
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control << EOF
Package: factory-game
Version: 1.0
Section: base
Priority: optional
Architecture: amd64
Maintainer: Developer <dev@example.com>
Description: A simple game using factory pattern
EOF
        dpkg-deb --build package factory-game.deb

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: factory-game-package
        path: build/factory-game.deb
