name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Create build directory
      run: mkdir -p build

    - name: Configure with CMake
      run: cd build && cmake ..

    - name: Build project
      run: cd build && make

    - name: Run Tank test
      run: cd build && ./test_Tank

    - name: Run GameFactory test
      run: cd build && ./test_GameFactory

    - name: Build main executable
      run: cd build && make main

    - name: Create DEB package
      run: |
        mkdir -p package/usr/bin
        cp build/main package/usr/bin/
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control << 'CONTROL_EOF'
Package: factory-game
Version: 1.0
Section: base
Priority: optional
Architecture: amd64
Maintainer: Developer <dev@example.com>
Description: A simple game using factory pattern
CONTROL_EOF
        dpkg-deb --build package factory-game.deb

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: factory-game-package
        path: build/factory-game.deb
